const _ = require('lodash');

const coinInfo = [
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Kucoin Shares',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'KCS'
  },
  {
    withdrawMinFee: 0.001,
    withdrawMinAmount: 0.002,
    withdrawFeeRate: 0.001,
    confirmationCount: 3,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Bitcoin',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BTC'
  },
  {
    withdrawMinFee: 0.01,
    withdrawMinAmount: 0.1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Ethereum',
    tradePrecision: 7,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ETH'
  },
  {
    withdrawMinFee: 0,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'NEO',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'NEO'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'I-House Token',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'IHT'
  },
  {
    withdrawMinFee: 0.05,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Nano',
    tradePrecision: 6,
    depositRemark: '',
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'XRB'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Fortuna',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'FOTA'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SingularityNET',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'AGI'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Aigang',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'AIX'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Enjin Coin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ENJ'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Experty',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'EXY'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 30,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Havven',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'HAV'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'High Performance Blockch',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'HPB'
  },
  {
    withdrawMinFee: 30,
    withdrawMinAmount: 200,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'JET8',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'J8T'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Red Pulse',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'RPX'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'THEKEY',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TKY'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Trinity',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TNC'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Zeepin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ZPT'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 300,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Alphacat',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ACAT'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'EthLend',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'LEND'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Chronobank',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TIME'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Credits',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CS'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'AChain',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ACT'
  },
  {
    withdrawMinFee: 1.8,
    withdrawMinAmount: 12,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Aeron',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ARN'
  },
  {
    withdrawMinFee: 25,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'aXpire',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'AXP'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'CanYa',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CAN'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'BitClave',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CAT'
  },
  {
    withdrawMinFee: 30,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'CargoX',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CXO'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Datum',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DAT'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'DeepBrain Chain',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DBC'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'EncrypGen',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DNA'
  },
  {
    withdrawMinFee: 100,
    withdrawMinAmount: 2000,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'DATA',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DTA'
  },
  {
    withdrawMinFee: 50,
    withdrawMinAmount: 350,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: "If there's a designated payment id, please add @PAYMENT_ID after the address of ETN which shall set as withdrawal address. i.e.etnXXXXXXXAddress@0000000000000000000000000000000000000000000000payment_id_example",
    infoUrl: null,
    name: 'Electroneum',
    tradePrecision: 2,
    depositRemark: 'Please send the deposit of ETN to the following address：\netnjvMPvGM68TZp59KDfWvQoNS7NFaEc9296CK4pSrfA4j5KgTguz5sZNEwC2KMW6iEn8gML7vASrT3gLxD3n9zs3M2PxMYVyH\nand you have to designate payment_id to the below information:',
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ETN'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'INS Ecosystem',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'INS'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Jibrel Network',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'JNT'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Qlink',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'QLC'
  },
  {
    withdrawMinFee: 500,
    withdrawMinAmount: 5000,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Telcoin',
    tradePrecision: 2,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TEL'
  },
  {
    withdrawMinFee: 50,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Dent',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DENT'
  },
  {
    withdrawMinFee: 32,
    withdrawMinAmount: 210,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Electrify.Asia',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ELEC'
  },
  {
    withdrawMinFee: 50,
    withdrawMinAmount: 1000,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'IOStoken',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'IOST'
  },
  {
    withdrawMinFee: 30,
    withdrawMinAmount: 200,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Loom Network',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'LOOM'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Pura',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PURA'
  },
  {
    withdrawMinFee: 14,
    withdrawMinAmount: 90,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'OriginTrail',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TRAC'
  },
  {
    withdrawMinFee: 8,
    withdrawMinAmount: 55,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SophiaTX',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SPHTX'
  },
  {
    withdrawMinFee: 30,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'carVertical',
    tradePrecision: 2,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CV'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Adbank',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ADB'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 200,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Block Array',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ARY'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'BOScoin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BOS'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Centra',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CTR'
  },
  {
    withdrawMinFee: 12,
    withdrawMinAmount: 80,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Debitum Network',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DEB'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'aelf',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ELF'
  },
  {
    withdrawMinFee: 4,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Gladius Token',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'GLA'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Hawala.Today',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'HAT'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'IUNGO',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ING'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'IoT Chain',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ITC'
  },
  {
    withdrawMinFee: 50,
    withdrawMinAmount: 1000,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SelfKey',
    tradePrecision: 4,
    depositRemark: "Please be aware that this address is only for depositing SelfKey (KEY), depositing other assets into this address will cause fund loss and it's not revertible.",
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'KEY'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Medicalchain',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'MTN'
  },
  {
    withdrawMinFee: 100,
    withdrawMinAmount: 500,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Odyssey',
    tradePrecision: 2,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'OCN'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Po.et',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'POE'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SunContract',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SNC'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Trade Token',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TIO'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'UTRUST',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'UTK'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Solaris',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'XLR'
  },
  {
    withdrawMinFee: 50,
    withdrawMinAmount: 300,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Zilliqa',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ZIL'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 200,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Cappasity',
    tradePrecision: 2,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CAPP'
  },
  {
    withdrawMinFee: 70,
    withdrawMinAmount: 500,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SwissBorg',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CHSB'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'CoinFi',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'COFI'
  },
  {
    withdrawMinFee: 6,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'DADI',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DADI'
  },
  {
    withdrawMinFee: 0.002,
    withdrawMinAmount: 0.05,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Dash',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DASH'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'eBitcoin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'EBTC'
  },
  {
    withdrawMinFee: 4,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'LOCIcoin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'LOCI'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Blockport',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BPT'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Covesting',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'COV'
  },
  {
    withdrawMinFee: 140,
    withdrawMinAmount: 1000,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Gatcoin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'GAT'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Hacken',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'HKN'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Oyster Pearl',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PRL'
  },
  {
    withdrawMinFee: 300,
    withdrawMinAmount: 2000,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SpherePay',
    tradePrecision: 2,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: false,
    coin: 'SAY'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'TrueFlip',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'TFL'
  },
  {
    withdrawMinFee: 8,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'WAX',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'WAX'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Aion',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'AION'
  },
  {
    withdrawMinFee: 35,
    withdrawMinAmount: 150,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'KickCoin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'KICK'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Restart Energy',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'MWAT'
  },
  {
    withdrawMinFee: 40,
    withdrawMinAmount: 300,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'HEROcoin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PLAY'
  },
  {
    withdrawMinFee: 40,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Pareto Network',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PARETO'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Revain',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'R'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'LAToken',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'LA'
  },
  {
    withdrawMinFee: 0.0005,
    withdrawMinAmount: 0.01,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Bitcoin Cash',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BCH'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Change',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CAG'
  },
  {
    withdrawMinFee: 0.005,
    withdrawMinAmount: 0.01,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Bitcoin God',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: false,
    enableDeposit: false,
    coin: 'GOD'
  },
  {
    withdrawMinFee: 30,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'CoinMeet',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'MEE'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Modum',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'MOD'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Publica',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PBL'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 0.5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Populous',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PPT'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Quantstamp',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'QSP'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'SONM',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SNM'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'SportyCo',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SPF'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Asch',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'XAS'
  },
  {
    withdrawMinFee: 0.005,
    withdrawMinAmount: 0.01,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'ABTC',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: false,
    enableDeposit: false,
    coin: 'ABTC'
  },
  {
    withdrawMinFee: 50,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Bounty0x',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BNTY'
  },
  {
    withdrawMinFee: 0.01,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Bitcoin Private',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: false,
    enableDeposit: false,
    coin: 'BTCP'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Dragonchain',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DRGN'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Nuls',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'NULS'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'ClearPoll',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'POLL'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 2,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Power Ledger',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'POWR'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Snovio',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SNOV'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'DeepOnion',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ONION'
  },
  {
    withdrawMinFee: 0.01,
    withdrawMinAmount: 0.1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Ethereum Classic',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ETC'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Ambrosus',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'AMB'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Stox',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'STX'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Elixir',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'ELIX'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'STK',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'STK'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Flixxo',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'FLIXX'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Genesis Vision',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'GVT'
  },
  {
    withdrawMinFee: 0.005,
    withdrawMinAmount: 0.01,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Bitcoin Diamond',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: false,
    enableDeposit: false,
    coin: 'BCD'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Confido',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CFD'
  },
  {
    withdrawMinFee: 0,
    withdrawMinAmount: 0.2,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'NeoGas',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'GAS'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Horizon State',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'HST'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Raiden Network',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'RDN'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Substratum',
    tradePrecision: 2,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SUB'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Unikoin Gold',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'UKG'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 0.2,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Walton',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'WTC'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Neblio',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'NEBL'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Polymath',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'POLY'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'RChain',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'RHOC'
  },
  {
    withdrawMinFee: 2,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'VeChain',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'VEN'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 50,
    withdrawFeeRate: 0.001,
    confirmationCount: 3,
    withdrawRemark: null,
    infoUrl: null,
    name: 'USDT',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'USDT'
  },
  {
    withdrawMinFee: 0.005,
    withdrawMinAmount: 0.01,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Bitcoin Gold',
    tradePrecision: 8,
    depositRemark: null,
    enableWithdraw: false,
    enableDeposit: false,
    coin: 'BTG'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Digibyte',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'DGB'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Everex',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'EVX'
  },
  {
    withdrawMinFee: 0.01,
    withdrawMinAmount: 0.1,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Hshare',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'HSR'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 0.5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Kyber Network',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'KNC'
  },
  {
    withdrawMinFee: 0.001,
    withdrawMinAmount: 0.1,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Litecoin',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'LTC'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Monetha',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'MTH'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 0.2,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'OmiseGO',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'OMG'
  },
  {
    withdrawMinFee: 10,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Request',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'REQ'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'BlockMason',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BCPT'
  },
  {
    withdrawMinFee: 0.1,
    withdrawMinAmount: 0.2,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Qtum',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'QTUM'
  },
  {
    withdrawMinFee: 5,
    withdrawMinAmount: 20,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Bytom',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BTM'
  },
  {
    withdrawMinFee: 3,
    withdrawMinAmount: 5,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Civic',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'CVC'
  },
  {
    withdrawMinFee: 0.01,
    withdrawMinAmount: 0.1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Ethereum Fog',
    tradePrecision: 6,
    depositRemark: null,
    enableWithdraw: false,
    enableDeposit: false,
    coin: 'ETF'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 1,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'TenXPay',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'PAY'
  },
  {
    withdrawMinFee: 0.5,
    withdrawMinAmount: 2,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'EOS',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'EOS'
  },
  {
    withdrawMinFee: 20,
    withdrawMinAmount: 100,
    withdrawFeeRate: 0.001,
    confirmationCount: 12,
    withdrawRemark: '',
    infoUrl: null,
    name: 'Status',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'SNT'
  },
  {
    withdrawMinFee: 1,
    withdrawMinAmount: 10,
    withdrawFeeRate: 0.001,
    confirmationCount: 6,
    withdrawRemark: null,
    infoUrl: null,
    name: 'Black Hole Coin',
    tradePrecision: 4,
    depositRemark: null,
    enableWithdraw: true,
    enableDeposit: true,
    coin: 'BHC'
  }
];

const coinMap = _.keyBy(coinInfo, d => d.coin);

module.exports = {
  coinMap
};
